Response.destroy_all
Question.destroy_all
Survey.destroy_all
User.destroy_all
Team.destroy_all
Category.destroy_all
# Create teams

team_1 = Team.create!(name: "Marketing")
team_2 = Team.create!(name: "Sales")
team_3 = Team.create!(name: "Finance")
team_4 = Team.create!(name: "HR")

# Create users


aude = User.create!(first_name: "Aude",last_name: "Idh", email: "aude.idh@gmail.com", password: "azerty", role: "super_user")
alex = User.create!(first_name: "Alex",last_name: "Grondin", email: "alex@mailinator.com", password: "azerty", role: "team_leader", team: team_1)
a1t1 = User.create!(first_name: "1",last_name: "team1", email: "1-team1@mailinator.com", password: "azerty", role: "team_member", team: team_1)
a2t1 = User.create!(first_name: "2",last_name: "team1", email: "2-team1@mailinator.com", password: "azerty", role: "team_member", team: team_1)
a3t1 = User.create!(first_name: "3",last_name: "team1", email: "3-team1@mailinator.com", password: "azerty", role: "team_member", team: team_1)
a4t1= User.create!(first_name: "4",last_name: "team1", email: "4-team1@mailinator.com", password: "azerty", role: "team_member", team: team_1)


l2 = User.create!(first_name: "l2",last_name: "team2", email: "l2-team2@mailinator.com", password: "azerty", role: "team_leader", team: team_2)
a1t2 = User.create!(first_name: "1",last_name: "team2", email: "1-team2@mailinator.com", password: "azerty", role: "team_member", team: team_2)
a2t2 = User.create!(first_name: "2",last_name: "team2", email: "2-team2@mailinator.com", password: "azerty", role: "team_member", team: team_2)
a3t2 = User.create!(first_name: "3",last_name: "team2", email: "3-team2@mailinator.com", password: "azerty", role: "team_member", team: team_2)
a4t2 = User.create!(first_name: "4",last_name: "team2", email: "4-team2@mailinator.com", password: "azerty", role: "team_member", team: team_2)

l3= User.create!(first_name: "l3",last_name: "team3", email: "l3-team3@mailinator.com", password: "azerty", role: "team_leader", team: team_3)
a1t3 = User.create!(first_name: "1",last_name: "team3", email: "1-team3@mailinator.com", password: "azerty", role: "team_member", team: team_3)
a2t3 = User.create!(first_name: "2",last_name: "team3", email: "2-team3@mailinator.com", password: "azerty", role: "team_member", team: team_3)
a3t3 = User.create!(first_name: "3",last_name: "team3", email: "3-team3@mailinator.com", password: "azerty", role: "team_member", team: team_3)
a4t3 = User.create!(first_name: "4",last_name: "team3", email: "4-team3@mailinator.com", password: "azerty", role: "team_member", team: team_3)


User.create!(first_name: "l4",last_name: "team4", email: "l4-team4@mailinator.com", password: "azerty", role: "team_leader", team: team_4)
a1t4 = User.create!(first_name: "1",last_name: "team4", email: "1-team4@mailinator.com", password: "azerty", role: "team_member", team: team_4)
a2t4 = User.create!(first_name: "2",last_name: "team4", email: "2-team4@mailinator.com", password: "azerty", role: "team_member", team: team_4)
a3t4 = User.create!(first_name: "3",last_name: "team4", email: "3-team4@mailinator.com", password: "azerty", role: "team_member", team: team_4)
a4t4 = User.create!(first_name: "4",last_name: "team4", email: "4-team4@mailinator.com", password: "azerty", role: "team_member", team: team_4)


# create categories


personal_growth = Category.create!(name: "Personal growth")
well = Category.create!(name: "Well being")
col = Category.create!(name: "Collaboration")
tool = Category.create!(name: "Tools & Processes")
enter = Category.create!(name: "Enterprise culture")

# categories.each do |category_name|
#  # create! categories
#  category = Category.create!(name: category_name)


#  # filling the surveys with category and questions
#  Survey.all.each do |survey|
#    question = Question.create!(category: category, text: "Are you happy?", survey: survey )
#    # giving 2 responses to the questions
#    Response.create!(rating: 5, question: question, user: survey.team.users.all.sample)
#    Response.create!(rating: 4, question: question, user: survey.team.users.all.sample)
#  end
# end

#create surveys / questions


survey_1 = Survey.create!(team: team_1)
  question_1 = Question.create!(category: personal_growth, text: "I feel like I can voice my opinion", survey: survey_1 )
  question_2 = Question.create!(category: well, text: "My direct manager cares about my well-being and support me when i am dealing with personal issues" , survey: survey_1 )
  question_3 =  Question.create!(category: col, text: "I can count on my colleagues when I need help", survey: survey_1 )
  question_4 =  Question.create!(category: tool, text: "I  have access to the resources needed to do my work properly", survey: survey_1 )
  question_5 = Question.create!(category: enter, text: "I understand how my work contributes to the goals of my organization", survey: survey_1 )

Response.create!(rating: rand(4..5), question: question_1, user: a1t1)
Response.create!(rating: rand(4..5), question: question_2, user: a1t1)
Response.create!(rating: rand(4..5), question: question_3, user: a1t1)
Response.create!(rating: rand(4..5), question: question_4, user: a1t1)
Response.create!(rating: rand(4..5), question: question_5, user: a1t1)
Response.create!(rating: rand(4..5), question: question_1, user: a2t1)
Response.create!(rating: rand(4..5), question: question_2, user: a2t1)
Response.create!(rating: rand(4..5), question: question_3, user: a2t1)
Response.create!(rating: rand(4..5), question: question_4, user: a2t1)
Response.create!(rating: rand(4..5), question: question_5, user: a2t1)
Response.create!(rating: rand(4..5), question: question_1, user: a3t1)
Response.create!(rating: rand(4..5), question: question_2, user: a3t1)
Response.create!(rating: rand(4..5), question: question_3, user: a3t1)
Response.create!(rating: rand(4..5), question: question_4, user: a3t1)
Response.create!(rating: rand(4..5), question: question_5, user: a3t1)
Response.create!(rating: rand(4..5), question: question_1, user: a4t1)
Response.create!(rating: rand(4..5), question: question_2, user: a4t1)
Response.create!(rating: rand(4..5), question: question_3, user: a4t1)
Response.create!(rating: rand(4..5), question: question_4, user: a4t1)
Response.create!(rating: rand(4..5), question: question_5, user: a4t1)



survey_2 = Survey.create!(team: team_1)
  question_6 =  Question.create!(category: personal_growth, text: "My organization celebrates team accomplishments as well as personal success", survey: survey_2 )
  question_7 =  Question.create!(category: well, text: "I have the flexibility to take time off when I need to" , survey: survey_2 )
  question_8 =  Question.create!(category: col, text: "I feel like I am part of a team", survey: survey_2 )
  question_9 =  Question.create!(category: tool, text: "The processes and tools provided are relevant  and helpful to accomplish my work", survey: survey_2 )
  question_10 =  Question.create!(category: enter, text: "I consider myself an ambassador for my organization", survey: survey_2 )

Response.create!(rating: rand(4..5), question: question_6, user: a1t1)
Response.create!(rating: rand(4..5), question: question_7, user: a1t1)
Response.create!(rating: rand(4..5), question: question_8, user: a1t1)
Response.create!(rating: rand(4..5), question: question_9, user: a1t1)
Response.create!(rating: rand(4..5), question: question_10, user: a1t1)
Response.create!(rating: rand(4..5), question: question_6, user: a2t1)
Response.create!(rating: rand(4..5), question: question_7, user: a2t1)
Response.create!(rating: rand(4..5), question: question_8, user: a2t1)
Response.create!(rating: rand(4..5), question: question_9, user: a2t1)
Response.create!(rating: rand(4..5), question: question_10, user: a2t1)
Response.create!(rating: rand(4..5), question: question_6, user: a3t1)
Response.create!(rating: rand(4..5), question: question_7, user: a3t1)
Response.create!(rating: rand(4..5), question: question_8, user: a3t1)
Response.create!(rating: rand(4..5), question: question_9, user: a3t1)
Response.create!(rating: rand(4..5), question: question_10, user: a3t1)
Response.create!(rating: rand(4..5), question: question_6, user: a4t1)
Response.create!(rating: rand(4..5), question: question_7, user: a4t1)
Response.create!(rating: rand(4..5), question: question_8, user: a4t1)
Response.create!(rating: rand(4..5), question: question_9, user: a4t1)
Response.create!(rating: rand(4..5), question: question_10, user: a4t1)

survey_3 = Survey.create!(team: team_1)
  question_11 =  Question.create!(category: personal_growth, text: "I feel like I can voice my opinion", survey: survey_3 )
  question_12 =  Question.create!(category: well, text: "I feel that I can maintain a healthy balance between work and my personal life" , survey: survey_3 )
  question_13 =  Question.create!(category: col, text: "I feel like I am part of a team", survey: survey_3 )
  question_14 =  Question.create!(category: tool, text: "I  have access to the resources needed to do my work properly", survey: survey_3 )
  question_15 =  Question.create!(category: enter, text: "Leaders demonstrate  a vision that motivates me", survey: survey_3 )

Response.create!(rating: rand(4..5), question: question_11, user: a1t1)
Response.create!(rating: rand(4..5), question: question_12, user: a1t1)
Response.create!(rating: rand(4..5), question: question_13, user: a1t1)
Response.create!(rating: rand(4..5), question: question_14, user: a1t1)
Response.create!(rating: rand(4..5), question: question_15, user: a1t1)
Response.create!(rating: rand(4..5), question: question_11, user: a2t1)
Response.create!(rating: rand(4..5), question: question_12, user: a2t1)
Response.create!(rating: rand(4..5), question: question_13, user: a2t1)
Response.create!(rating: rand(4..5), question: question_14, user: a2t1)
Response.create!(rating: rand(4..5), question: question_15, user: a2t1)
Response.create!(rating: rand(4..5), question: question_11, user: a3t1)
Response.create!(rating: rand(4..5), question: question_12, user: a3t1)
Response.create!(rating: rand(4..5), question: question_13, user: a3t1)
Response.create!(rating: rand(4..5), question: question_14, user: a3t1)
Response.create!(rating: rand(4..5), question: question_15, user: a3t1)
Response.create!(rating: rand(4..5), question: question_11, user: a4t1)
Response.create!(rating: rand(4..5), question: question_12, user: a4t1)
Response.create!(rating: rand(4..5), question: question_13, user: a4t1)
Response.create!(rating: rand(4..5), question: question_14, user: a4t1)
Response.create!(rating: rand(4..5), question: question_15, user: a4t1)

survey_4 = Survey.create!(team: team_1)
  question_16 =  Question.create!(category: personal_growth, text: "My organization celebrates team accomplishments as well as personal success", survey: survey_4 )
  question_17 =  Question.create!(category: well, text: "My direct manager cares about my well-being and support me when i am dealing with personal issues" , survey: survey_4 )
  question_18 =  Question.create!(category: col, text: "I can count on my colleagues when I need help", survey: survey_4 )
  question_19 =  Question.create!(category: tool, text: "The processes and tools provided are relevant  and helpful to accomplish my work", survey: survey_4 )
  question_20 =  Question.create!(category: enter, text: "I understand how my work contributes to the goals of my organization", survey: survey_4 )

Response.create!(rating: rand(4..5), question: question_16, user: a1t1)
Response.create!(rating: rand(4..5), question: question_17, user: a1t1)
Response.create!(rating: rand(4..5), question: question_18, user: a1t1)
Response.create!(rating: rand(4..5), question: question_19, user: a1t1)
Response.create!(rating: rand(4..5), question: question_20, user: a1t1)
Response.create!(rating: rand(4..5), question: question_16, user: a2t1)
Response.create!(rating: rand(4..5), question: question_17, user: a2t1)
Response.create!(rating: rand(4..5), question: question_18, user: a2t1)
Response.create!(rating: rand(4..5), question: question_19, user: a2t1)
Response.create!(rating: rand(4..5), question: question_20, user: a2t1)
Response.create!(rating: rand(4..5), question: question_16, user: a3t1)
Response.create!(rating: rand(4..5), question: question_17, user: a3t1)
Response.create!(rating: rand(4..5), question: question_18, user: a3t1)
Response.create!(rating: rand(4..5), question: question_19, user: a3t1)
Response.create!(rating: rand(4..5), question: question_20, user: a3t1)
Response.create!(rating: rand(4..5), question: question_16, user: a4t1)
Response.create!(rating: rand(4..5), question: question_17, user: a4t1)
Response.create!(rating: rand(4..5), question: question_18, user: a4t1)
Response.create!(rating: rand(4..5), question: question_19, user: a4t1)
Response.create!(rating: rand(4..5), question: question_20, user: a4t1)

survey_5 = Survey.create!(team: team_1)
  question_21 =  Question.create!(category: personal_growth, text: "I feel like I can voice my opinion", survey: survey_5 )
  question_22 =  Question.create!(category: well, text: "I have the flexibility to take time off when I need to" , survey: survey_5 )
  question_23 =  Question.create!(category: col, text: "Communication among the team is honest and transparent", survey: survey_5 )
  question_24 =  Question.create!(category: tool, text: "The processes and tools provided are relevant  and helpful to accomplish my work", survey: survey_5 )
  question_25 =  Question.create!(category: enter, text: "Leaders demonstrate  a vision that motivates me", survey: survey_5 )

Response.create!(rating: rand(4..5), question: question_21, user: a1t1)
Response.create!(rating: rand(4..5), question: question_22, user: a1t1)
Response.create!(rating: rand(4..5), question: question_23, user: a1t1)
Response.create!(rating: rand(4..5), question: question_24, user: a1t1)
Response.create!(rating: rand(4..5), question: question_25, user: a1t1)
Response.create!(rating: rand(4..5), question: question_21, user: a2t1)
Response.create!(rating: rand(4..5), question: question_22, user: a2t1)
Response.create!(rating: rand(4..5), question: question_23, user: a2t1)
Response.create!(rating: rand(4..5), question: question_24, user: a2t1)
Response.create!(rating: rand(4..5), question: question_25, user: a2t1)
Response.create!(rating: rand(4..5), question: question_21, user: a3t1)
Response.create!(rating: rand(4..5), question: question_22, user: a3t1)
Response.create!(rating: rand(4..5), question: question_23, user: a3t1)
Response.create!(rating: rand(4..5), question: question_24, user: a3t1)
Response.create!(rating: rand(4..5), question: question_25, user: a3t1)
Response.create!(rating: rand(4..5), question: question_21, user: a4t1)
Response.create!(rating: rand(4..5), question: question_22, user: a4t1)
Response.create!(rating: rand(4..5), question: question_23, user: a4t1)
Response.create!(rating: rand(4..5), question: question_24, user: a4t1)
Response.create!(rating: rand(4..5), question: question_25, user: a4t1)

survey_6 = Survey.create!(team: team_2)
  question_26 =  Question.create!(category: personal_growth, text: "My organization celebrates team accomplishments as well as personal success", survey: survey_6 )
  question_27 =  Question.create!(category: well, text: "I feel that I can maintain a healthy balance between work and my personal life" , survey: survey_6)
  question_28 =  Question.create!(category: col, text: "I feel like I am part of a team", survey: survey_6 )
  question_29 =  Question.create!(category: tool, text: "I  have access to the resources needed to do my work properly", survey: survey_6 )
  question_30 =  Question.create!(category: enter, text: "I understand how my work contributes to the goals of my organization", survey: survey_6 )

Response.create!(rating: rand(1..3), question: question_26, user: a1t2)
Response.create!(rating: rand(1..3), question: question_27, user: a1t2)
Response.create!(rating: rand(1..3), question: question_28, user: a1t2)
Response.create!(rating: rand(1..3), question: question_29, user: a1t2)
Response.create!(rating: rand(1..3), question: question_30, user: a1t2)
Response.create!(rating: rand(1..3), question: question_26, user: a2t2)
Response.create!(rating: rand(1..3), question: question_27, user: a2t2)
Response.create!(rating: rand(1..3), question: question_28, user: a2t2)
Response.create!(rating: rand(1..3), question: question_29, user: a2t2)
Response.create!(rating: rand(1..3), question: question_30, user: a2t2)
Response.create!(rating: rand(1..3), question: question_26, user: a3t2)
Response.create!(rating: rand(1..3), question: question_27, user: a3t2)
Response.create!(rating: rand(1..3), question: question_28, user: a3t2)
Response.create!(rating: rand(1..3), question: question_29, user: a3t2)
Response.create!(rating: rand(1..3), question: question_30, user: a3t2)
Response.create!(rating: rand(1..3), question: question_26, user: a4t2)
Response.create!(rating: rand(1..3), question: question_27, user: a4t2)
Response.create!(rating: rand(1..3), question: question_28, user: a4t2)
Response.create!(rating: rand(1..3), question: question_29, user: a4t2)
Response.create!(rating: rand(1..3), question: question_30, user: a4t2)

survey_7 = Survey.create!(team: team_2)
  question_31 =  Question.create!(category: personal_growth, text: "I feel like I can voice my opinion", survey: survey_7 )
  question_32 =  Question.create!(category: well, text: "I have the flexibility to take time off when I need to" , survey: survey_7 )
  question_33 =  Question.create!(category: col, text: "I can count on my colleagues when I need help", survey: survey_7 )
  question_34 =  Question.create!(category: tool, text: "I am satisfied with the level of comfort and safety in my physical workplace", survey: survey_7 )
  question_35 =  Question.create!(category: enter, text: "I consider myself an ambassador for my organization", survey: survey_7 )

Response.create!(rating: rand(1..3), question: question_31, user: a1t2)
Response.create!(rating: rand(1..3), question: question_32, user: a1t2)
Response.create!(rating: rand(1..3), question: question_33, user: a1t2)
Response.create!(rating: rand(1..3), question: question_34, user: a1t2)
Response.create!(rating: rand(1..3), question: question_35, user: a1t2)
Response.create!(rating: rand(1..3), question: question_31, user: a2t2)
Response.create!(rating: rand(1..3), question: question_32, user: a2t2)
Response.create!(rating: rand(1..3), question: question_33, user: a2t2)
Response.create!(rating: rand(1..3), question: question_34, user: a2t2)
Response.create!(rating: rand(1..3), question: question_35, user: a2t2)
Response.create!(rating: rand(1..3), question: question_31, user: a3t2)
Response.create!(rating: rand(1..3), question: question_32, user: a3t2)
Response.create!(rating: rand(1..3), question: question_33, user: a3t2)
Response.create!(rating: rand(1..3), question: question_34, user: a3t2)
Response.create!(rating: rand(1..3), question: question_35, user: a3t2)
Response.create!(rating: rand(1..3), question: question_31, user: a4t2)
Response.create!(rating: rand(1..3), question: question_32, user: a4t2)
Response.create!(rating: rand(1..3), question: question_33, user: a4t2)
Response.create!(rating: rand(1..3), question: question_34, user: a4t2)
Response.create!(rating: rand(1..3), question: question_35, user: a4t2)

survey_8 = Survey.create!(team: team_2)
  question_36 =  Question.create!(category: personal_growth, text: "My organization celebrates team accomplishments as well as personal success", survey: survey_8 )
  question_37 =  Question.create!(category: well, text: "My direct manager cares about my well-being and support me when i am dealing with personal issues" , survey: survey_8 )
  question_38 =  Question.create!(category: col, text: "Communication among the team is honest and transparent", survey: survey_8 )
  question_39 =  Question.create!(category: tool, text: "The processes and tools provided are relevant  and helpful to accomplish my work", survey: survey_8 )
  question_40 =  Question.create!(category: enter, text: "Leaders demonstrate  a vision that motivates me", survey: survey_8 )

Response.create!(rating: rand(1..3), question: question_36, user: a1t2)
Response.create!(rating: rand(1..3), question: question_37, user: a1t2)
Response.create!(rating: rand(1..3), question: question_38, user: a1t2)
Response.create!(rating: rand(1..3), question: question_39, user: a1t2)
Response.create!(rating: rand(1..3), question: question_40, user: a1t2)
Response.create!(rating: rand(1..3), question: question_36, user: a2t2)
Response.create!(rating: rand(1..3), question: question_37, user: a2t2)
Response.create!(rating: rand(1..3), question: question_38, user: a2t2)
Response.create!(rating: rand(1..3), question: question_39, user: a2t2)
Response.create!(rating: rand(1..3), question: question_40, user: a2t2)
Response.create!(rating: rand(1..3), question: question_36, user: a3t2)
Response.create!(rating: rand(1..3), question: question_37, user: a3t2)
Response.create!(rating: rand(1..3), question: question_38, user: a3t2)
Response.create!(rating: rand(1..3), question: question_39, user: a3t2)
Response.create!(rating: rand(1..3), question: question_40, user: a3t2)
Response.create!(rating: rand(1..3), question: question_36, user: a4t2)
Response.create!(rating: rand(1..3), question: question_37, user: a4t2)
Response.create!(rating: rand(1..3), question: question_38, user: a4t2)
Response.create!(rating: rand(1..3), question: question_39, user: a4t2)
Response.create!(rating: rand(1..3), question: question_40, user: a4t2)

survey_9 = Survey.create!(team: team_2)
  question_41 =  Question.create!(category: personal_growth, text: "My organization celebrates team accomplishments as well as personal success", survey: survey_9 )
  question_42 =  Question.create!(category: well, text: "I have the flexibility to take time off when I need to" , survey: survey_9 )
  question_43 =  Question.create!(category: col, text: "I feel like I am part of a team", survey: survey_9 )
  question_44 =  Question.create!(category: tool, text: "The processes and tools provided are relevant  and helpful to accomplish my work", survey: survey_9 )
  question_45 =  Question.create!(category: enter, text: "I understand how my work contributes to the goals of my organization", survey: survey_9 )

Response.create!(rating: rand(1..3), question: question_41, user: a1t2)
Response.create!(rating: rand(1..3), question: question_42, user: a1t2)
Response.create!(rating: rand(1..3), question: question_43, user: a1t2)
Response.create!(rating: rand(1..3), question: question_44, user: a1t2)
Response.create!(rating: rand(1..3), question: question_45, user: a1t2)
Response.create!(rating: rand(1..3), question: question_41, user: a2t2)
Response.create!(rating: rand(1..3), question: question_42, user: a2t2)
Response.create!(rating: rand(1..3), question: question_43, user: a2t2)
Response.create!(rating: rand(1..3), question: question_44, user: a2t2)
Response.create!(rating: rand(1..3), question: question_45, user: a2t2)
Response.create!(rating: rand(1..3), question: question_41, user: a3t2)
Response.create!(rating: rand(1..3), question: question_42, user: a3t2)
Response.create!(rating: rand(1..3), question: question_43, user: a3t2)
Response.create!(rating: rand(1..3), question: question_44, user: a3t2)
Response.create!(rating: rand(1..3), question: question_45, user: a3t2)
Response.create!(rating: rand(1..3), question: question_41, user: a4t2)
Response.create!(rating: rand(1..3), question: question_42, user: a4t2)
Response.create!(rating: rand(1..3), question: question_43, user: a4t2)
Response.create!(rating: rand(1..3), question: question_44, user: a4t2)
Response.create!(rating: rand(1..3), question: question_45, user: a4t2)

survey_10 = Survey.create!(team: team_3)
  question_46 =  Question.create!(category: personal_growth, text: "I feel like I can voice my opinion", survey: survey_10 )
  question_47 =  Question.create!(category: well, text: "I feel that I can maintain a healthy balance between work and my personal life" , survey: survey_10 )
  question_48 =  Question.create!(category: col, text: "Communication among the team is honest and transparent", survey: survey_10 )
  question_49 =  Question.create!(category: tool, text: "I am satisfied with the level of comfort and safety in my physical workplace", survey: survey_10 )
  question_50 =  Question.create!(category: enter, text: "Leaders demonstrate  a vision that motivates me", survey: survey_10 )

Response.create!(rating: rand(2..4), question: question_46, user: a1t3)
Response.create!(rating: rand(2..4), question: question_47, user: a1t3)
Response.create!(rating: rand(2..4), question: question_48, user: a1t3)
Response.create!(rating: rand(2..4), question: question_49, user: a1t3)
Response.create!(rating: rand(2..4), question: question_50, user: a1t3)
Response.create!(rating: rand(2..4), question: question_46, user: a2t3)
Response.create!(rating: rand(2..4), question: question_47, user: a2t3)
Response.create!(rating: rand(2..4), question: question_48, user: a2t3)
Response.create!(rating: rand(2..4), question: question_49, user: a2t3)
Response.create!(rating: rand(2..4), question: question_50, user: a2t3)
Response.create!(rating: rand(2..4), question: question_46, user: a3t3)
Response.create!(rating: rand(2..4), question: question_47, user: a3t3)
Response.create!(rating: rand(2..4), question: question_48, user: a3t3)
Response.create!(rating: rand(2..4), question: question_49, user: a3t3)
Response.create!(rating: rand(2..4), question: question_50, user: a3t3)
Response.create!(rating: rand(2..4), question: question_46, user: a4t3)
Response.create!(rating: rand(2..4), question: question_47, user: a4t3)
Response.create!(rating: rand(2..4), question: question_48, user: a4t3)
Response.create!(rating: rand(2..4), question: question_49, user: a4t3)
Response.create!(rating: rand(2..4), question: question_50, user: a4t3)

survey_11 = Survey.create!(team: team_3)
  question_51 =  Question.create!(category: personal_growth, text: "I feel like I can voice my opinion", survey: survey_11 )
  question_52 =  Question.create!(category: well, text: "I have the flexibility to take time off when I need to" , survey: survey_11 )
  question_53 =  Question.create!(category: col, text: "Communication among the team is honest and transparent", survey: survey_11 )
  question_54 =  Question.create!(category: tool, text: "I  have access to the resources needed to do my work properly", survey: survey_11 )
  question_55 =  Question.create!(category: enter, text: "I consider myself an ambassador for my organization", survey: survey_11 )

Response.create!(rating: rand(1..3), question: question_51, user: a1t3)
Response.create!(rating: rand(1..3), question: question_52, user: a1t3)
Response.create!(rating: rand(1..3), question: question_53, user: a1t3)
Response.create!(rating: rand(1..3), question: question_54, user: a1t3)
Response.create!(rating: rand(1..3), question: question_55, user: a1t3)
Response.create!(rating: rand(1..3), question: question_51, user: a2t3)
Response.create!(rating: rand(1..3), question: question_52, user: a2t3)
Response.create!(rating: rand(1..3), question: question_53, user: a2t3)
Response.create!(rating: rand(1..3), question: question_54, user: a2t3)
Response.create!(rating: rand(1..3), question: question_55, user: a2t3)
Response.create!(rating: rand(1..3), question: question_51, user: a3t3)
Response.create!(rating: rand(1..3), question: question_52, user: a3t3)
Response.create!(rating: rand(1..3), question: question_53, user: a3t3)
Response.create!(rating: rand(1..3), question: question_54, user: a3t3)
Response.create!(rating: rand(1..3), question: question_55, user: a3t3)
Response.create!(rating: rand(1..3), question: question_51, user: a4t3)
Response.create!(rating: rand(1..3), question: question_52, user: a4t3)
Response.create!(rating: rand(1..3), question: question_53, user: a4t3)
Response.create!(rating: rand(1..3), question: question_54, user: a4t3)
Response.create!(rating: rand(1..3), question: question_55, user: a4t3)

survey_12 = Survey.create!(team: team_3)
  question_56 =  Question.create!(category: personal_growth, text: "My organization celebrates team accomplishments as well as personal success", survey: survey_12 )
  question_57 =  Question.create!(category: well, text: "My direct manager cares about my well-being and support me when i am dealing with personal issues" , survey: survey_12 )
  question_58 =  Question.create!(category: col, text: "I feel like I am part of a team", survey: survey_12 )
  question_59 =  Question.create!(category: tool, text: "I  have access to the resources needed to do my work properly", survey: survey_12 )
  question_60 =  Question.create!(category: enter, text: "I understand how my work contributes to the goals of my organization", survey: survey_12 )

Response.create!(rating: rand(1..3), question: question_56, user: a1t3)
Response.create!(rating: rand(1..3), question: question_57, user: a1t3)
Response.create!(rating: rand(1..3), question: question_58, user: a1t3)
Response.create!(rating: rand(1..3), question: question_59, user: a1t3)
Response.create!(rating: rand(1..3), question: question_60, user: a1t3)
Response.create!(rating: rand(1..3), question: question_56, user: a2t3)
Response.create!(rating: rand(1..3), question: question_57, user: a2t3)
Response.create!(rating: rand(1..3), question: question_58, user: a2t3)
Response.create!(rating: rand(1..3), question: question_59, user: a2t3)
Response.create!(rating: rand(1..3), question: question_60, user: a2t3)
Response.create!(rating: rand(1..3), question: question_56, user: a3t3)
Response.create!(rating: rand(1..3), question: question_57, user: a3t3)
Response.create!(rating: rand(1..3), question: question_58, user: a3t3)
Response.create!(rating: rand(1..3), question: question_59, user: a3t3)
Response.create!(rating: rand(1..3), question: question_60, user: a3t3)
Response.create!(rating: rand(1..3), question: question_56, user: a4t3)
Response.create!(rating: rand(1..3), question: question_57, user: a4t3)
Response.create!(rating: rand(1..3), question: question_58, user: a4t3)
Response.create!(rating: rand(1..3), question: question_59, user: a4t3)
Response.create!(rating: rand(1..3), question: question_60, user: a4t3)

survey_13 = Survey.create!(team: team_4)
  question_61 =  Question.create!(category: personal_growth, text: "I feel like I can voice my opinion", survey: survey_13 )
  question_62 =  Question.create!(category: well, text: "I feel that I can maintain a healthy balance between work and my personal life" , survey: survey_13 )
  question_63 =  Question.create!(category: col, text: "I can count on my colleagues when I need help", survey: survey_13 )
  question_64 =  Question.create!(category: tool, text: "I am satisfied with the level of comfort and safety in my physical workplace", survey: survey_13 )
  question_65 =  Question.create!(category: enter, text: "Leaders demonstrate  a vision that motivates me", survey: survey_13 )

Response.create!(rating: rand(1..3), question: question_61, user: a1t4)
Response.create!(rating: rand(1..3), question: question_62, user: a1t4)
Response.create!(rating: rand(1..3), question: question_63, user: a1t4)
Response.create!(rating: rand(1..3), question: question_64, user: a1t4)
Response.create!(rating: rand(1..3), question: question_65, user: a1t4)
Response.create!(rating: rand(1..3), question: question_61, user: a2t4)
Response.create!(rating: rand(1..3), question: question_62, user: a2t4)
Response.create!(rating: rand(1..3), question: question_63, user: a2t4)
Response.create!(rating: rand(1..3), question: question_64, user: a2t4)
Response.create!(rating: rand(1..3), question: question_65, user: a2t4)
Response.create!(rating: rand(1..3), question: question_61, user: a3t4)
Response.create!(rating: rand(1..3), question: question_62, user: a3t4)
Response.create!(rating: rand(1..3), question: question_63, user: a3t4)
Response.create!(rating: rand(1..3), question: question_64, user: a3t4)
Response.create!(rating: rand(1..3), question: question_65, user: a3t4)
Response.create!(rating: rand(1..3), question: question_61, user: a4t4)
Response.create!(rating: rand(1..3), question: question_62, user: a4t4)
Response.create!(rating: rand(1..3), question: question_63, user: a4t4)
Response.create!(rating: rand(1..3), question: question_64, user: a4t4)
Response.create!(rating: rand(1..3), question: question_65, user: a4t4)

survey_14 = Survey.create!(team: team_4)
  question_66 =  Question.create!(category: personal_growth, text: "My organization celebrates team accomplishments as well as personal success", survey: survey_14 )
  question_67 =  Question.create!(category: well, text: "I have the flexibility to take time off when I need to" , survey: survey_14 )
  question_68 =  Question.create!(category: col, text: "I feel like I am part of a team", survey: survey_14 )
  question_69 =  Question.create!(category: tool, text: "I  have access to the resources needed to do my work properly", survey: survey_14 )
  question_70 =  Question.create!(category: enter, text: "I understand how my work contributes to the goals of my organization", survey: survey_14 )

Response.create!(rating: rand(1..3), question: question_66, user: a1t4)
Response.create!(rating: rand(1..3), question: question_67, user: a1t4)
Response.create!(rating: rand(1..3), question: question_68, user: a1t4)
Response.create!(rating: rand(1..3), question: question_69, user: a1t4)
Response.create!(rating: rand(1..3), question: question_70, user: a1t4)
Response.create!(rating: rand(1..3), question: question_66, user: a2t4)
Response.create!(rating: rand(1..3), question: question_67, user: a2t4)
Response.create!(rating: rand(1..3), question: question_68, user: a2t4)
Response.create!(rating: rand(1..3), question: question_69, user: a2t4)
Response.create!(rating: rand(1..3), question: question_70, user: a2t4)
Response.create!(rating: rand(1..3), question: question_66, user: a3t4)
Response.create!(rating: rand(1..3), question: question_67, user: a3t4)
Response.create!(rating: rand(1..3), question: question_68, user: a3t4)
Response.create!(rating: rand(1..3), question: question_69, user: a3t4)
Response.create!(rating: rand(1..3), question: question_70, user: a3t4)
Response.create!(rating: rand(1..3), question: question_66, user: a4t4)
Response.create!(rating: rand(1..3), question: question_67, user: a4t4)
Response.create!(rating: rand(1..3), question: question_68, user: a4t4)
Response.create!(rating: rand(1..3), question: question_69, user: a4t4)
Response.create!(rating: rand(1..3), question: question_70, user: a4t4)

survey_15 = Survey.create!(team: team_4)
  question_71 =  Question.create!(category: personal_growth, text: "I feel like I can voice my opinion", survey: survey_15 )
  question_72 =  Question.create!(category: well, text: "My direct manager cares about my well-being and support me when i am dealing with personal issues" , survey: survey_15 )
  question_73 =  Question.create!(category: col, text: "I feel like I am part of a team", survey: survey_15 )
  question_74 =  Question.create!(category: tool, text: "I am satisfied with the level of comfort and safety in my physical workplace", survey: survey_15 )
  question_75 =  Question.create!(category: enter, text: "I consider myself an ambassador for my organization", survey: survey_15 )

Response.create!(rating: rand(1..5), question: question_71, user: a1t4)
Response.create!(rating: rand(1..5), question: question_72, user: a1t4)
Response.create!(rating: rand(1..5), question: question_73, user: a1t4)
Response.create!(rating: rand(1..5), question: question_74, user: a1t4)
Response.create!(rating: rand(1..5), question: question_75, user: a1t4)
Response.create!(rating: rand(1..5), question: question_71, user: a2t4)
Response.create!(rating: rand(1..5), question: question_72, user: a2t4)
Response.create!(rating: rand(1..5), question: question_73, user: a2t4)
Response.create!(rating: rand(1..5), question: question_74, user: a2t4)
Response.create!(rating: rand(1..5), question: question_75, user: a2t4)
Response.create!(rating: rand(1..5), question: question_71, user: a3t4)
Response.create!(rating: rand(1..5), question: question_72, user: a3t4)
Response.create!(rating: rand(1..5), question: question_73, user: a3t4)
Response.create!(rating: rand(1..5), question: question_74, user: a3t4)
Response.create!(rating: rand(1..5), question: question_75, user: a3t4)
Response.create!(rating: rand(1..5), question: question_71, user: a4t4)
Response.create!(rating: rand(1..5), question: question_72, user: a4t4)
Response.create!(rating: rand(1..5), question: question_73, user: a4t4)
Response.create!(rating: rand(1..5), question: question_74, user: a4t4)
Response.create!(rating: rand(1..5), question: question_75, user: a4t4)










